### ISSUE TITLE
Assembly option values not being pushed

### ISSUE THREAD

**Issue by jpgutti** [vtex-apps/product-customizer#51]
**Describe the bug**
It seems that the input text is not being attached to the product when added to cart.

**Expected behavior**
Expected the value of the attachment to be attached to the product when added to cart. But neither the orderform nor the checkout itself has the property. Not even to handle that by javascript as it is described in the README

**Additional context**
I've notice that in a scenario where we use the `add-to-cart-button` the action is made but with no attachment sent. And in a scenario where we use the `buy-button` from store-component, the same behavior is seen, but this time with a new object sent **assemblyOptions**, but also empty.

**Comment by klzns** [comment]
Hi @jpgutti currently product-customizer uses the Assembly Options API which will substitute the Attachments API. 

So you if you open a Checkout page and open the Dev Console and type:

```js
vtexjs.checkout.orderForm.items[0]
```

The property `assemblies` will have the information regarding the attachments. 

We have a known issue right now that our cart page doesn't render any information about the `assemblies` object which causes confusion that it didn't work out.

If there's nothing inside the `assemblies` property in the Checkout pages, let me know pasting a link to a product in your workspace so I can reproduce the issue. Thanks!

**Comment by jpgutti** [comment]
Hey @klzns ...
So, I've noticed the disclaimer about that in the documentation...
The problem is that in the checkout the item object doesn't have nothing in assemblies objects...

**Comment by jpgutti** [comment]
@klzns The link to the product -> https://joao--bennemann.myvtex.com/aaa/p

**Comment by jpgutti** [comment]
@klzns Any updates?

**Comment by klzns** [comment]
@jpgutti yes, it's a bug in our API. I'll let you know when I have more updates on this.

**Comment by leonardorente** [comment]
Hi @klzns can you share with us an estimate date? 
This fix is mandatory to publish our client store.

Thanks!

**Comment by leonardorente** [comment]
Hi @klzns any update about this issue?

**Comment by klzns** [comment]
@leonardorente we fixed the issue, can you try again and see if it's alright now?

**Comment by jpgutti** [comment]
@klzns It's working properly now! Tks for the effort! :D

**Comment by leonardorente** [comment]
Thank you guys!

**Comment by klzns** [comment]
Thanks for reporting!
