### ISSUE TITLE
Manageable text for add attachment button

### ISSUE THREAD

**Issue by jpgutti** [vtex-apps/product-customizer#55]
Nowadays the button to add attachment comes with a hardcoded text **Add**, not being able to change or even use css to handle the displayed text or messages builder.

Expected to be manageable due the fact that not all stores will be in english.

**Comment by rsantiago88** [comment]
Hi!

Would you guys have an update about this issue ?

Thank you.

**Comment by klzns** [comment]
@jpgutti That's a good suggestion. What do you like the text to be? Just so I can solve your use case?

**Comment by jpguttione** [comment]
@klzns It'd be great if you guys could make that text somehow editable through messages builder or site editor... not being attached to the name of the service itself... 
And of course, removing as well the hard coded text **Add**. haha

**Comment by klzns** [comment]
Yes, I understand. I would like to know which text would input

**Comment by jpguttione** [comment]
@klzns Since the app is about the attachments itself, and not service... I think that the default text could be something like "Additional Info" or "Adicionar Informação".
Don't forget about the **remove** button as well 🤓

**Comment by klzns** [comment]
Done! Thanks

**Comment by jpguttione** [comment]
@klzns I couldn't be able to change the message neither from messages builder nor from GraphQL IDE in Admin. Could you check that out please?

**Comment by klzns** [comment]
@jpguttione I have the same issue. I'm checking with the team responsible. I let you know

**Comment by klzns** [comment]
There's an issue with our cache related to messages. The team might have a fix by tomorrow.

You can bust the cache by installing or linking an app in the workspace and it should reflect the change to get the new message.

**Comment by klzns** [comment]
I'll let this open until you say it's solved

**Comment by jpguttione** [comment]
@klzns By the time still not working.

I'll let you know when it works.

**Comment by klzns** [comment]
@jpguttione have you tried linking an app in your workspace? or installing an app?

**Comment by jpguttione** [comment]
@klzns By linking **an** App you mean the related App? Or Any of them?

I tried unlink and link...
I installed the related App to workspace...
Nothing change, not even through messages builder or the Graph IDE

**Comment by klzns** [comment]
Are you passing the arguments of the mutation like this?

(you might need to change the `"to": "en-US"` to the language of the store)

```json
{
 "args": {
   "to": "en-US",
   "messages": [
     {
       "srcLang": "en-DV",
       "srcMessage": "store/product-customizer.add-assembly",
       "targetMessage": "Testing",
       "context": "vtex.product-customizer@2.x"
     }
   ]
 }
}
```

**Comment by jpguttione** [comment]
@klzns Tried the args that you sent and even after 15 min nothing change :/

**Comment by jpguttione** [comment]
@klzns You may close de issue, it finally worked. :)

But now I'm having the same issue as before, the assemblie option is not being pushed to the orderForm.

Could you take a look, please?

I opened an issue related to this, we can discuss it there :)
