### ISSUE TITLE
Not adding input values with special characters "+" and "$"

### ISSUE THREAD

**Issue by jpguttione** [vtex-apps/product-customizer#59]
**Describe the bug**
The input value is not being pushed to orderForm again.

**To Reproduce**

1. Setup a product with an attachment 
2. Render the component block in product page 
3. Input the value and add product to cart
4. Go to checkout and see assemblies options inside itens object in orderForm.

**Expected behavior**
Expected the value to be pushed with product infos to the orderForm.

**Comment by klzns** [comment]
Can you provide a workspace with the product in question?

**Comment by jpguttione** [comment]
@klzns 
https://bennemann.myvtex.com/pasta-couro-notebook-berlin-preto-e-azul/p
https://test--bennemann.myvtex.com/pasta-couro-notebook-berlin-preto-e-azul/p

**Comment by klzns** [comment]
I'm checking here. The issue is caused by the usage of special characters. I'll let you know of any updates.

**Comment by jpguttione** [comment]
@klzns in the name of the attachment?

We had it that way cause of the issue of the text of the button.

**Comment by klzns** [comment]
>@klzns in the name of the attachment?

Yes

**Comment by klzns** [comment]
I've tested here with a product with an attachment without special chars and it worked fine. 

Let me know if changing the name of the attachment to something without special chars it's a viable option.

**Comment by jpguttione** [comment]
@klzns You can be sure that the special caracteres are the "+" and "$" sign? Can I keep the name of the attachment "Personalização"? Without the "+ R$40"

**Comment by klzns** [comment]
@jpguttione Yes, "Personalização" will work fine 👍

**Comment by jpguttione** [comment]
@klzns I'm just waiting for the cache to test it. I'll let you know if everything works fine so you may close the issue :)

**Comment by jpguttione** [comment]
@klzns Sorry for the delay!
Everything is working fine! You may close the issue! Thank you! :)

**Comment by klzns** [comment]
Thanks for the feedback :)
